<script src="<?= base_url();?>/public/frontend/assets/js/vendor/jquery-3.5.1.min.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/vendor/waypoints.min.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/bootstrap.bundle.min.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/jquery.meanmenu.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/owl.carousel.min.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/jquery.fancybox.min.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/isotope.pkgd.min.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/parallax.min.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/backToTop.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/jquery.counterup.min.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/ajax-form.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/wow.min.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/imagesloaded.pkgd.min.js"></script>
<script src="<?= base_url();?>/public/frontend/assets/js/main.js"></script>